### ISSUE TITLE
運行問題

### ISSUE THREAD

**Issue by eason042** [will258012/TrainDisplayUpdated#1]
在10月的CSL更新以後，我的系統就沒有顯示車輛停靠站了，請問該如何解決呢?

**Comment by will258012** [comment]
能麻煩發送一下你的日誌檔案以及相關的截圖嗎？ 謝謝！
https://steamcommunity.com/sharedfiles/filedetails/?id=3198388677

**Comment by eason042** [comment]
謝謝你，但剛才它神奇的恢復了

Will ***@***.***>於 令和6年11月29日週五，22:31寫道：

**Comment by will258012** [comment]
Okay, but I'd like to know, has this happened more than once, or just this one time?
好的，但想再問一下，這個情況是出現不只一次嗎，還是只是剛剛那一次

**Comment by eason042** [comment]
後來我是發現只要在程式車站那一空格打幾個空格就可以正常顯示，沒記錯的話是10月的更新後無法顯示

Will ***@***.***>於 令和6年11月29日週五，22:54寫道：

**Comment by will258012** [comment]
你好，我們經過測試發現將你所說的設定置空後就會出現問題，會進行修復

**Comment by will258012** [comment]
已修復，請核查
